[package]
name = "aic_security"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
rand = "0.8"
sha2 = "0.10"
thiserror = "1.0"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"

[lib]
name = "aic_security"
crate-type = ["copylib", "rlib"]